version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: cron
      cronjob: '20 8 * * 2'
  - package-ecosystem: julia
    directories:
      - '/'
      - '/docs'
      - '/test'
      - '/benchmark'
    schedule:
      interval: cron
      cronjob: '20 8 * * 2'
