name = "ContinuousNormalizingFlows"
uuid = "00b1973d-5b2e-40bf-8604-5c9c1d8f50ac"
authors = ["Hossein Pourbozorg <prbzrg@gmail.com> and contributors"]
version = "0.26.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
ScientificTypesBase = "30f210dd-8aff-4c5f-94ba-8e64358c1161"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
ContinuousNormalizingFlowsCUDAExt = "CUDA"

[compat]
ADTypes = "1"
CUDA = "5"
ChainRulesCore = "1"
ComponentArrays = "0.15"
ComputationalResources = "0.3"
DataFrames = "1"
Dates = "1"
DifferentiationInterface = "0.6"
Distributions = "0.25"
DistributionsAD = "0.6"
Enzyme = "0.13"
EnzymeCore = "0.8"
FillArrays = "1"
LinearAlgebra = "1"
Lux = "1"
LuxCore = "1"
MLJBase = "1"
MLJModelInterface = "1"
MLUtils = "0.4"
NNlib = "0.9"
Optimisers = "0.4"
Optimization = "4"
OptimizationOptimisers = "0.3"
OrdinaryDiffEqDefault = "1"
Random = "1"
SciMLBase = "2"
SciMLSensitivity = "7"
ScientificTypesBase = "3"
Statistics = "1"
julia = "1.10"
